import { createGlyphFontRenderer } from '@/glyphwiki/renderFontGlyph'

export const renderIpamjmFont = await createGlyphFontRenderer({
  indexGzPath: 'src/fonts/ipamjm/glyph-index.txt.gz',
  fonts: [
    {
      fontPath: 'src/fonts/ipamjm/ipamjm.ttf',
      fontGzPath: 'src/fonts/ipamjm/ipamjm.ttf.gz',
    },
  ],
  // Generated by:
  // fontforge -script scripts/dump_render_box.py src/fonts/ipamjm/ipamjm.ttf
  renderBox: {
    viewBoxSize: 1024,
    fontSize: 1024,
    ascender: 901,
    baseline: 0,
  },
})
