import { createGlyphFontRenderer } from '@/glyphwiki/renderFontGlyph'
import { createGlyphPathShardRenderer } from '@/glyphwiki/renderGlyphPathShard'

const rendererConfig = {
  indexGzPath: 'src/fonts/ipamjm/glyph-index.txt.gz',
  fonts: [
    {
      fontPath: 'src/fonts/ipamjm/ipamjm.ttf',
      fontGzPath: 'src/fonts/ipamjm/ipamjm.ttf.gz',
    },
  ],
  // Generated by:
  // fontforge -script scripts/dump_render_box.py src/fonts/ipamjm/ipamjm.ttf
  renderBox: {
    viewBoxSize: 1024,
    fontSize: 1024,
    ascender: 901,
    baseline: 0,
  },
}

let fallbackRendererPromise:
  | ReturnType<typeof createGlyphFontRenderer>
  | undefined

async function renderFromLocalFont(name: string) {
  if (!fallbackRendererPromise) {
    const current = createGlyphFontRenderer(rendererConfig).catch((error) => {
      if (fallbackRendererPromise === current) fallbackRendererPromise = undefined
      throw error
    })
    fallbackRendererPromise = current
  }
  return (await fallbackRendererPromise)(name)
}

const renderFromShard = createGlyphPathShardRenderer({
  source: 'ipamjm',
  renderBox: rendererConfig.renderBox,
  fallback: renderFromLocalFont,
})

export async function renderIpamjmFont(name: string) {
  return renderFromShard(name)
}
