import IdsFinder from '../components/IdsFinder'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <nav>
          <h1>Mojidata IDS Find</h1>
          <p>Find the characters with the given IDS.</p>
          <dl>
            <dt>IDS Unary Operators</dt>
            <dd>〾↔↷</dd>
            <dt>IDS Binary Operators</dt>
            <dd>⿰⿱⿴⿵⿶⿷⿸⿹⿺⿻</dd>
            <dt>IDS Ternary Operators</dt>
            <dd>⿲⿳</dd>
          </dl>
          <IdsFinder />
        </nav>
        {children}
      </body>
    </html>
  )
}
