#!/bin/sh
set -eux

jigmo_zip="Jigmo-20250912.zip"

# check command dependencies
if ! type woff2_compress >/dev/null 2>&1; then
  echo "Please install woff2_compress" >&2
  exit 1
fi

cd "$(dirname "$0")/.."
scripts/download "$jigmo_zip"
mkdir -p src/fonts/jigmo
unzip -d 'src/fonts/jigmo' -o "cache/$jigmo_zip" 'Jigmo.ttf' 'Jigmo2.ttf' 'Jigmo3.ttf'
gzip -kf \
  'src/fonts/jigmo/Jigmo.ttf' \
  'src/fonts/jigmo/Jigmo2.ttf' \
  'src/fonts/jigmo/Jigmo3.ttf'
scripts/build-jigmo-index
