#!/bin/sh
set -eu

cd "$(dirname "$0")/.."
scripts/build-glyph-index \
  'src/fonts/jigmo/glyph-index.txt.gz' \
  'src/fonts/jigmo/Jigmo.ttf' \
  'src/fonts/jigmo/Jigmo2.ttf' \
  'src/fonts/jigmo/Jigmo3.ttf'
