import { MojidataResults } from './mojidata'

void ([
  {
    char: '台',
    UCS: 'U+53F0',
    aj1: {
      CID: 2886,
      jp90: 2886,
      jp90_V: null,
      jp04: 2886,
      jp04_V: null,
      mac_jp90: 2886,
      mac_jp90_V: null,
      mac_jp04: 2886,
      mac_jp04_V: null,
    },
    ids: [
      {
        IDS: '⿱厶口',
        source: 'GHJKTV',
      },
    ],
    ids_similar: [],
    ids_comment: [],
    ivs: [
      {
        char: '台󠄀',
        IVS: '53F0_E0100',
        collection: 'Adobe-Japan1',
        code: 'CID+2886',
      },
    ],
    svs_cjkci: [],
    unihan: {
      kHanYu: '10575.020',
      kIRGHanyuDaZidian: '10575.020',
      kIRGKangXi: '0172.130',
      kKangXi: '0172.130',
      kCihaiT: '244.401',
      kSBGY: '059.15 100.45',
      kNelson: '0848',
      kCowles: '4423',
      kMatthews: '6008',
      kGSR: '0976p',
      kFennIndex: '490.08',
      kKarlgren: '181',
      kMeyerWempe: '3198',
      kLau: '3104',
      kMorohashi: '03246',
      kDaeJaweon: '0384.010',
      kIRGDaeJaweon: '0384.010',
      kIRGDaiKanwaZiten: '03246',
      kCangjie: 'IR',
      kPhonetic: '1373 1374 1549',
      kUnihanCore2020: 'GHJKMPT',
      kFourCornerCode: '2360.0',
      kFrequency: '2',
      kGradeLevel: '3',
      kHKGlyph: '0490',
      kIRG_GSource: 'G0-4C28',
      kIRG_JSource: 'J0-4266',
      kIRG_TSource: 'T1-463A',
      kRSUnicode: '30.2',
      kTotalStrokes: '5',
      kIRG_KSource: 'K0-773B',
      kIRG_KPSource: 'KP0-F0D1',
      kIRG_VSource: 'V1-4E3D',
      kIRG_HSource: 'HB1-A578',
      kIICore: 'AGTJHKMP',
      kTGH: '2013:342',
      kKoreanName: '2015',
      kEACC: '283B7D',
      kTaiwanTelegraph: '0669',
      kKPS0: 'F0D1',
      kBigFive: 'A578',
      kCCCII: '213538',
      kCNS1986: '1-463A',
      kCNS1992: '1-463A',
      kGB0: '4408',
      kGB1: '8875',
      kJis0: '3470',
      kJoyoKanji: '2010',
      kKSC0: '8727',
      kMainlandTelegraph: '0669',
      kXerox: '242:156',
      kRSAdobe_Japan1_6: 'C+2886+28.2.3 C+2886+30.3.2',
      kRSKangXi: '30.2',
      kCantonese: 'toi4',
      kDefinition: 'platform; unit; term of address',
      kMandarin: 'tái',
      kHanyuPinyin: '10575.020:yí,tái,sì',
      kTGHZ2013: '356.090:tāi 356.120,356.130,356.140,356.150:tái',
      kXHC1983: '1108.010:tāi 1108.070:tái',
      kVietnamese: 'thai',
      kHangul: '태:0N',
      kTang: '*təi',
      kJapaneseKun: 'UTENA YOROKOBU',
      kJapaneseOn: 'DAI TAI I',
      kHanyuPinlu: 'tái(530)',
      kKorean: 'THAY I',
      kSemanticVariant: 'U+81FA<kHKGlyph,kLau',
      kTraditionalVariant: 'U+53F0 U+6AAF U+81FA U+98B1',
      kSimplifiedVariant: 'U+53F0',
    },
    unihan_fts: [
      [
        'U+38CD',
        '㣍',
        'kDefinition',
        '(ancient form of 台) a raised platform, eminent; exalted, name of a star',
      ],
      ['U+53F0', '台', 'kTraditionalVariant', 'U+53F0 U+6AAF U+81FA U+98B1'],
      ['U+53F0', '台', 'kSimplifiedVariant', 'U+53F0'],
      ['U+6AAF', '檯', 'kSimplifiedVariant', 'U+53F0'],
      ['U+81FA', '臺', 'kSemanticVariant', 'U+53F0<kHKGlyph,kLau'],
      ['U+81FA', '臺', 'kSimplifiedVariant', 'U+53F0'],
      ['U+98B1', '颱', 'kSimplifiedVariant', 'U+53F0 U+310D7'],
    ],
    unihan_variant: [
      ['kSemanticVariant', 'U+81FA', '臺', 'kHKGlyph,kLau'],
      ['kSimplifiedVariant', 'U+53F0', '台'],
      ['kTraditionalVariant', 'U+53F0', '台'],
      ['kTraditionalVariant', 'U+6AAF', '檯'],
      ['kTraditionalVariant', 'U+81FA', '臺'],
      ['kTraditionalVariant', 'U+98B1', '颱'],
    ],
    unihan_variant_inverse: [
      ['kSemanticVariant', 'U+81FA', '臺', 'kHKGlyph,kLau'],
      ['kSimplifiedVariant', 'U+53F0', '台'],
      ['kSimplifiedVariant', 'U+6AAF', '檯'],
      ['kSimplifiedVariant', 'U+81FA', '臺'],
      ['kSimplifiedVariant', 'U+98B1', '颱'],
      ['kTraditionalVariant', 'U+53F0', '台'],
    ],
    joyo: [
      {
        音訓: 'ダイ',
        例: ['台地', '灯台', '一台'],
        備考: '',
      },
      {
        音訓: 'タイ',
        例: ['台風', '舞台'],
        備考: '',
      },
    ],
    joyo_kangxi: ['臺'],
    joyo_kangxi_inverse: [],
    doon: [
      {
        書きかえる漢語: '颱風',
        書きかえた漢語: '台風',
        採用した文書: '',
      },
    ],
    nyukan: [
      {
        正字の種類: '異体字',
        簡体字等の文字コード等: '365c',
        簡体字等のUCS: '㙜',
        正字の文字コード等: '53f0',
        正字のUCS: '台',
        順位: 1,
      },
      {
        正字の種類: '異体字',
        簡体字等の文字コード等: '3675',
        簡体字等のUCS: '㙵',
        正字の文字コード等: '53f0',
        正字のUCS: '台',
        順位: 1,
      },
      {
        正字の種類: '異体字',
        簡体字等の文字コード等: '38cd',
        簡体字等のUCS: '㣍',
        正字の文字コード等: '53f0',
        正字のUCS: '台',
        順位: 1,
      },
      {
        正字の種類: '異体字',
        簡体字等の文字コード等: '74f5',
        簡体字等のUCS: '瓵',
        正字の文字コード等: '53f0',
        正字のUCS: '台',
        順位: 1,
      },
      {
        正字の種類: '異体字',
        簡体字等の文字コード等: '9c90',
        簡体字等のUCS: '鲐',
        正字の文字コード等: '53f0',
        正字のUCS: '台',
        順位: 2,
      },
      {
        正字の種類: '異体字',
        簡体字等の文字コード等: '2693c',
        簡体字等のUCS: '𦤼',
        正字の文字コード等: '53f0',
        正字のUCS: '台',
        順位: 1,
      },
    ],
    tghb: [
      {
        序号: '0342',
        规范字: '台',
        级: 1,
        笔画: 5,
        註解: null,
        异体字: [
          {
            繁体字: '台',
            异体字: '台',
            註解: null,
          },
          {
            繁体字: '臺',
            异体字: '臺',
            註解: null,
          },
          {
            繁体字: '颱',
            异体字: '颱',
            註解: null,
          },
          {
            繁体字: '檯',
            异体字: '檯',
            註解: null,
          },
        ],
      },
    ],
    mji: [
      {
        文字: '台',
        MJ文字図形名: 'MJ008038',
        対応するUCS: 'U+53F0',
        実装したUCS: 'U+53F0',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
        戸籍統一文字番号: '037700',
        住基ネット統一文字コード: 'J+53F0',
        入管正字コード: '0x53F0',
        入管外字コード: null,
        漢字施策: '常用漢字',
        対応する互換漢字: null,
        X0213: '1-34-70',
        X0213_包摂連番: null,
        X0213_包摂区分: 0,
        X0212: null,
        MJ文字図形バージョン: '1',
        登記統一文字番号: '00037700',
        '部首・内画数': [[30, 2]],
        総画数: 5,
        読み: ['ダイ', 'タイ', 'イ', 'シ', 'ジ', 'うてな'],
        大漢和: 3246,
        日本語漢字辞典: 1286,
        新大字典: 1738,
        大字源: 1057,
        大漢語林: 1248,
        更新履歴: [],
        備考: null,
        mjsm: [['JIS包摂規準UCS統合規則', 'U+53F0', '台']],
      },
    ],
    mjsm_inverse: [
      {
        表: 'JIS包摂規準UCS統合規則',
        文字: '台',
        MJ文字図形名: 'MJ008038',
        対応するUCS: 'U+53F0',
        実装したUCS: 'U+53F0',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '法務省告示582号別表第四_一',
        文字: '㙵',
        MJ文字図形名: 'MJ000542',
        対応するUCS: 'U+3675',
        実装したUCS: 'U+3675',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '法務省告示582号別表第四_一',
        文字: '㣍',
        MJ文字図形名: 'MJ001098',
        対応するUCS: 'U+38CD',
        実装したUCS: 'U+38CD',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '法務省告示582号別表第四_一',
        文字: '瓵',
        MJ文字図形名: 'MJ017560',
        対応するUCS: 'U+74F5',
        実装したUCS: 'U+74F5',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '法務省告示582号別表第四_一',
        文字: '𦤼',
        MJ文字図形名: 'MJ045952',
        対応するUCS: 'U+2693C',
        実装したUCS: 'U+2693C',
        実装したMoji_JohoコレクションIVS: '2693C_E0100',
        実装したSVS: null,
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '㙵',
        MJ文字図形名: 'MJ000542',
        対応するUCS: 'U+3675',
        実装したUCS: 'U+3675',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '䑓',
        MJ文字図形名: 'MJ003905',
        対応するUCS: 'U+4453',
        実装したUCS: 'U+4453',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '坮',
        MJ文字図形名: 'MJ008971',
        対応するUCS: 'U+576E',
        実装したUCS: 'U+576E',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '臺',
        MJ文字図形名: 'MJ021314',
        対応するUCS: 'U+81FA',
        実装したUCS: 'U+81FA',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '𡋛',
        MJ文字図形名: 'MJ033008',
        対応するUCS: 'U+212DB',
        実装したUCS: 'U+212DB',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '𡌫',
        MJ文字図形名: 'MJ033055',
        対応するUCS: 'U+2132B',
        実装したUCS: 'U+2132B',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '𡌬',
        MJ文字図形名: 'MJ033056',
        対応するUCS: 'U+2132C',
        実装したUCS: 'U+2132C',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '𡎲',
        MJ文字図形名: 'MJ033119',
        対応するUCS: 'U+213B2',
        実装したUCS: 'U+213B2',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '𡐉',
        MJ文字図形名: 'MJ033158',
        対応するUCS: 'U+21409',
        実装したUCS: 'U+21409',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '𡔼',
        MJ文字図形名: 'MJ033305',
        対応するUCS: 'U+2153C',
        実装したUCS: 'U+2153C',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '𦥄',
        MJ文字図形名: 'MJ045957',
        対応するUCS: 'U+26944',
        実装したUCS: 'U+26944',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '辞書類等による関連字',
        文字: '坮',
        MJ文字図形名: 'MJ008971',
        対応するUCS: 'U+576E',
        実装したUCS: 'U+576E',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
    ],
    kdpv: {
      'cjkvi/traditional': ['台', '檯', '臺', '颱'],
      'cjkvi/variant': ['𠘭', '𠮯'],
      'hydcd/borrowed': ['嗣', '始', '能'],
      'hydzd/proper': ['怡', '瓵', '鮐'],
      'hydzd/traditional': ['檯', '臺', '颱'],
      'hydzd/variant': ['㣍', '邰'],
      'jisx0212/variant': ['坮', '臺'],
      'jisx0213/variant': ['䑓', '臺'],
      'joyo/variant': ['臺'],
      'jp/borrowed-reverse': ['颱'],
      'jp/old-style': ['臺󠄀'],
      'koseki/variant': ['臺'],
      'sawndip/regular': ['𬆗'],
      'twedu/regular': ['檯', '臺', '颱'],
      'twedu/variant': ['㣍', '𠘭', '𠮯'],
      '~cjkvi/simplified': ['檯', '臺', '颱'],
      '~cjkvi/traditional': ['台'],
    },
  },
  {
    char: '神',
    UCS: 'U+795E',
    aj1: {
      CID: 2566,
      jp90: 2566,
      jp90_V: null,
      jp04: 2566,
      jp04_V: null,
      mac_jp90: 2566,
      mac_jp90_V: null,
      mac_jp04: 2566,
      mac_jp04_V: null,
    },
    ids: [
      {
        IDS: '⿰礻申',
        source: 'GHJTV',
      },
      {
        IDS: '⿰示申',
        source: 'K',
      },
    ],
    ids_similar: [],
    ids_comment: [],
    ivs: [
      {
        char: '神󠄀',
        IVS: '795E_E0100',
        collection: 'Adobe-Japan1',
        code: 'CID+8580',
      },
      {
        char: '神󠄁',
        IVS: '795E_E0101',
        collection: 'Adobe-Japan1',
        code: 'CID+2566',
      },
      {
        char: '神󠄂',
        IVS: '795E_E0102',
        collection: 'Hanyo-Denshi',
        code: 'JA3132',
      },
      {
        char: '神󠄃',
        IVS: '795E_E0103',
        collection: 'Hanyo-Denshi',
        code: 'JC8928',
      },
      {
        char: '神󠄂',
        IVS: '795E_E0102',
        collection: 'Moji_Joho',
        code: 'MJ018811',
      },
      {
        char: '神󠄃',
        IVS: '795E_E0103',
        collection: 'Moji_Joho',
        code: 'MJ030211',
      },
    ],
    svs_cjkci: [
      {
        SVS_char: '神︀',
        SVS: '795E_FE00',
        CJKCI_char: '神',
        CJKCI: 'U+FA19',
      },
    ],
    unihan: {
      kHanYu: '42392.010',
      kIRGHanyuDaZidian: '42392.010',
      kIRGKangXi: '0842.030',
      kKangXi: '0842.030',
      kSBGY: '102.24',
      kNelson: '3245',
      kCowles: '3835',
      kMatthews: '5716',
      kGSR: '0385j',
      kFennIndex: '444.08',
      kMeyerWempe: '2631',
      kLau: '2663',
      kMorohashi: "24673'",
      kDaeJaweon: '1261.020',
      kIRGDaeJaweon: '1261.020',
      kIRGDaiKanwaZiten: "24673'",
      kCangjie: 'IFLWL',
      kPhonetic: '1126',
      kFenn: '824B',
      kUnihanCore2020: 'GHJKMPT',
      kFourCornerCode: '3520.6',
      kFrequency: '2',
      kGradeLevel: '3',
      kHKGlyph: '2869',
      kIRG_GSource: 'G0-4971',
      kIRG_JSource: 'J0-3F40',
      kIRG_TSource: 'T1-572E',
      kRSUnicode: '113.5',
      kTotalStrokes: '9',
      kIRG_KSource: 'K0-636A',
      kIRG_KPSource: 'KP0-E5D1',
      kIRG_VSource: 'V1-6121',
      kIRG_HSource: 'HB1-AFAB',
      kIICore: 'AGTJHKMP',
      kTGH: '2013:1711',
      kEACC: '214E6B',
      kTaiwanTelegraph: '4377',
      kKPS0: 'E5D1',
      kBigFive: 'AFAB',
      kCCCII: '214E6B',
      kCNS1986: '1-572E',
      kCNS1992: '1-572E',
      kGB0: '4181',
      kGB1: '4181',
      kJis0: '3132',
      kJoyoKanji: '2010',
      kKSC0: '6774',
      kKoreanEducationHanja: '2007',
      kMainlandTelegraph: '4377',
      kXerox: '242:364',
      kRSAdobe_Japan1_6: 'C+2566+113.4.5',
      kRSKangXi: '113.5',
      kCantonese: 'san4',
      kDefinition: 'spirit, god, supernatural being',
      kMandarin: 'shén',
      kHanyuPinyin: '42392.010:shén,shēn',
      kTGHZ2013: '331.060:shén',
      kXHC1983: '1018.040:shén',
      kVietnamese: 'thần',
      kHangul: '신:0E',
      kTang: '*jhin',
      kJapaneseKun: 'KAMI KOU TAMASHII',
      kJapaneseOn: 'SHIN JIN',
      kHanyuPinlu: 'shén(846) shen(30)',
      kKorean: 'SIN',
    },
    unihan_fts: [
      ['U+FA19', '神', 'kCompatibilityVariant', 'U+795E'],
      ['U+FA19', '神', 'kJinmeiyoKanji', '2010:U+795E'],
    ],
    unihan_variant: [],
    unihan_variant_inverse: [
      ['kCompatibilityVariant', 'U+FA19', '神'],
      ['kJinmeiyoKanji', 'U+FA19', '神'],
    ],
    joyo: [
      {
        音訓: 'シン',
        例: ['神聖', '神経', '精神'],
        備考: 'お神酒（みき）',
      },
      {
        音訓: 'ジン',
        例: ['神社', '神宮', '神通力'],
        備考: '神楽（かぐら）',
      },
      {
        音訓: 'かみ',
        例: ['神', '神様', '貧乏神'],
        備考: '神奈川（かながわ）県',
      },
      {
        音訓: 'かん',
        例: ['神主'],
        備考: '',
      },
      {
        音訓: 'こう',
        例: ['神々しい'],
        備考: '',
      },
    ],
    joyo_kangxi: ['神'],
    joyo_kangxi_inverse: [],
    doon: [],
    nyukan: [
      {
        正字の種類: '類字',
        簡体字等の文字コード等: '4625',
        簡体字等のUCS: '䘥',
        正字の文字コード等: '795e',
        正字のUCS: '神',
        順位: 1,
      },
      {
        正字の種類: '類字',
        簡体字等の文字コード等: '8876',
        簡体字等のUCS: '衶',
        正字の文字コード等: '795e',
        正字のUCS: '神',
        順位: 1,
      },
    ],
    tghb: [
      {
        序号: '1711',
        规范字: '神',
        级: 1,
        笔画: 9,
        註解: null,
        异体字: [],
      },
    ],
    mji: [
      {
        文字: '神',
        MJ文字図形名: 'MJ018811',
        対応するUCS: 'U+795E',
        実装したUCS: 'U+795E',
        実装したMoji_JohoコレクションIVS: '795E_E0102',
        実装したSVS: null,
        戸籍統一文字番号: '275430',
        住基ネット統一文字コード: 'J+795E',
        入管正字コード: '0x795E',
        入管外字コード: null,
        漢字施策: '常用漢字',
        対応する互換漢字: null,
        X0213: '1-31-32',
        X0213_包摂連番: null,
        X0213_包摂区分: 0,
        X0212: null,
        MJ文字図形バージョン: '1',
        登記統一文字番号: '00275430',
        '部首・内画数': [[113, 5]],
        総画数: 9,
        読み: ['シン', 'ジン', 'かみ', 'かん', 'こう'],
        大漢和: 24673,
        日本語漢字辞典: 8102,
        新大字典: 11203,
        大字源: 6708,
        大漢語林: 7880,
        更新履歴: ['Ver.005.02 「実装したMoji_JohoIVS」を追加'],
        備考: null,
        mjsm: [['JIS包摂規準UCS統合規則', 'U+795E', '神']],
      },
      {
        文字: '神︀',
        MJ文字図形名: 'MJ030211',
        対応するUCS: 'U+795E',
        実装したUCS: 'U+FA19',
        実装したMoji_JohoコレクションIVS: '795E_E0103',
        実装したSVS: '795E_FE00',
        戸籍統一文字番号: '275870',
        住基ネット統一文字コード: 'J+FA19',
        入管正字コード: '0xFA19',
        入管外字コード: null,
        漢字施策: '人名用漢字',
        対応する互換漢字: 'U+FA19',
        X0213: '1-89-28',
        X0213_包摂連番: null,
        X0213_包摂区分: 0,
        X0212: null,
        MJ文字図形バージョン: '1',
        登記統一文字番号: '00275870',
        '部首・内画数': [[113, 5]],
        総画数: 10,
        読み: ['シン', 'ジン', 'かみ', 'かん', 'こう'],
        大漢和: 24673,
        日本語漢字辞典: 8103,
        新大字典: 11204,
        大字源: 6709,
        大漢語林: 7881,
        更新履歴: [
          'Ver.003.01 「対応するUCS」を変更',
          'Ver.005.02  「実装したMoji_JohoIVS」を追加',
        ],
        備考: null,
        mjsm: [
          ['戸籍統一文字情報_親字正字', 'U+795E', '神'],
          ['JIS包摂規準UCS統合規則', 'U+FA19', '神'],
        ],
      },
    ],
    mjsm_inverse: [
      {
        表: 'JIS包摂規準UCS統合規則',
        文字: '神',
        MJ文字図形名: 'MJ018811',
        対応するUCS: 'U+795E',
        実装したUCS: 'U+795E',
        実装したMoji_JohoコレクションIVS: '795E_E0102',
        実装したSVS: null,
      },
      {
        表: '法務省告示582号別表第四_二',
        文字: '䘥',
        MJ文字図形名: 'MJ004408',
        対応するUCS: 'U+4625',
        実装したUCS: 'U+4625',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '法務省告示582号別表第四_二',
        文字: '衶',
        MJ文字図形名: 'MJ023909',
        対応するUCS: 'U+8876',
        実装したUCS: 'U+8876',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '神︀',
        MJ文字図形名: 'MJ030211',
        対応するUCS: 'U+795E',
        実装したUCS: 'U+FA19',
        実装したMoji_JohoコレクションIVS: '795E_E0103',
        実装したSVS: '795E_FE00',
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '𥙍',
        MJ文字図形名: 'MJ042995',
        対応するUCS: 'U+2564D',
        実装したUCS: 'U+2564D',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '𥙍',
        MJ文字図形名: 'MJ042995',
        対応するUCS: 'U+2564D',
        実装したUCS: 'U+2564D',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '𥚞',
        MJ文字図形名: 'MJ043026',
        対応するUCS: 'U+2569E',
        実装したUCS: 'U+2569E',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '𥛃',
        MJ文字図形名: 'MJ043040',
        対応するUCS: 'U+256C3',
        実装したUCS: 'U+256C3',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '𥛠',
        MJ文字図形名: 'MJ043057',
        対応するUCS: 'U+256E0',
        実装したUCS: 'U+256E0',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '戸籍統一文字情報_親字正字',
        文字: '𥜩',
        MJ文字図形名: 'MJ043097',
        対応するUCS: 'U+25729',
        実装したUCS: 'U+25729',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '辞書類等による関連字',
        文字: '𥙍',
        MJ文字図形名: 'MJ042995',
        対応するUCS: 'U+2564D',
        実装したUCS: 'U+2564D',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '辞書類等による関連字',
        文字: '𥚞',
        MJ文字図形名: 'MJ043026',
        対応するUCS: 'U+2569E',
        実装したUCS: 'U+2569E',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '辞書類等による関連字',
        文字: '𥛃',
        MJ文字図形名: 'MJ043040',
        対応するUCS: 'U+256C3',
        実装したUCS: 'U+256C3',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '辞書類等による関連字',
        文字: '𥛠',
        MJ文字図形名: 'MJ043057',
        対応するUCS: 'U+256E0',
        実装したUCS: 'U+256E0',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '辞書類等による関連字',
        文字: '𥜩',
        MJ文字図形名: 'MJ043097',
        対応するUCS: 'U+25729',
        実装したUCS: 'U+25729',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
    ],
    kdpv: {
      'cjkvi/variant': ['𥚞'],
      'hydcd/borrowed': ['申'],
      'hydzd/variant': ['𥙍', '𥚞', '𥛃', '𥛠', '𥜩'],
      'jinmei2/variant': ['神'],
      'jisx0213/variant': ['神'],
      'joyo/variant': ['神'],
      'jp/new-style': ['神󠄁'],
      'jp/old-style': ['神󠄀'],
      'jp/old-style/compat': ['神'],
      'koseki/variant': ['神'],
      'sawndip/regular': ['抻'],
      'twedu/variant': ['䰠', '柛', '𥙍', '𥛃', '𥛠', '𥜩', '𥞁', '𫋵'],
    },
  },
  {
    char: '叱',
    UCS: 'U+53F1',
    aj1: {
      CID: 2276,
      jp90: 2276,
      jp90_V: null,
      jp04: 2276,
      jp04_V: null,
      mac_jp90: 2276,
      mac_jp90_V: null,
      mac_jp04: 2276,
      mac_jp04_V: null,
    },
    ids: [
      {
        IDS: '⿰口𠤎',
        source: 'GHJKT',
      },
      {
        IDS: '⿰口七',
        source: 'V',
      },
    ],
    ids_similar: [],
    ids_comment: [
      'U+53F1(V)=U+20B9F(GJ)',
      'U+53F1(V) was ^⿰口𠤎$ before Unicode 11.0',
    ],
    ivs: [
      {
        char: '叱󠄀',
        IVS: '53F1_E0100',
        collection: 'Adobe-Japan1',
        code: 'CID+2276',
      },
      {
        char: '叱󠄁',
        IVS: '53F1_E0101',
        collection: 'Adobe-Japan1',
        code: 'CID+7692',
      },
      {
        char: '叱󠄂',
        IVS: '53F1_E0102',
        collection: 'Hanyo-Denshi',
        code: 'JA2824',
      },
      {
        char: '叱󠄃',
        IVS: '53F1_E0103',
        collection: 'Hanyo-Denshi',
        code: 'JTAEA9',
      },
      {
        char: '叱󠄂',
        IVS: '53F1_E0102',
        collection: 'Moji_Joho',
        code: 'MJ008039',
      },
      {
        char: '叱󠄃',
        IVS: '53F1_E0103',
        collection: 'Moji_Joho',
        code: 'MJ008040',
      },
    ],
    svs_cjkci: [
      {
        SVS_char: '叱︀',
        SVS: '53F1_FE00',
        CJKCI_char: '叱',
        CJKCI: 'U+2F83A',
      },
    ],
    unihan: {
      kHanYu: '10572.060',
      kIRGHanyuDaZidian: '10572.060',
      kIRGKangXi: '0173.020',
      kKangXi: '0173.020',
      kNelson: '0873',
      kMatthews: '1046',
      kGSR: '0400e',
      kFennIndex: '73.09',
      kMeyerWempe: '274c',
      kMorohashi: '03248',
      kDaeJaweon: '0384.020',
      kIRGDaeJaweon: '0384.020',
      kIRGDaiKanwaZiten: '03248',
      kCangjie: 'RP',
      kPhonetic: '75',
      kFenn: '317K',
      kUnihanCore2020: 'GHJKMPT',
      kFourCornerCode: '6401.0',
      kHKGlyph: '0489',
      kIRG_GSource: 'G0-5F33',
      kIRG_JSource: 'J0-3C38',
      kIRG_TSource: 'T1-4639',
      kRSUnicode: '30.2',
      kTotalStrokes: '5',
      kIRG_KSource: 'K0-726A',
      kIRG_KPSource: 'KP0-EBBC',
      kIRG_VSource: 'V1-4E3E',
      kIRG_HSource: 'HB1-A577',
      kIICore: 'AGTJHKMP',
      kTGH: '2013:3539',
      kKoreanName: '2015',
      kEACC: '21353A',
      kTaiwanTelegraph: '0667',
      kKPS0: 'EBBC',
      kBigFive: 'A577',
      kCCCII: '21353A',
      kCNS1986: '1-4639',
      kCNS1992: '1-4639',
      kGB0: '6319',
      kGB1: '6319',
      kJis0: '2824',
      kJoyoKanji: 'U+20B9F',
      kKSC0: '8274',
      kMainlandTelegraph: '0667',
      kXerox: '262:364',
      kRSAdobe_Japan1_6:
        'C+2276+21.2.3 C+2276+30.3.2 V+7692+21.2.3 V+7692+30.3.2',
      kRSKangXi: '30.2',
      kCantonese: 'cik1',
      kDefinition: 'scold, shout at, bawl out',
      kMandarin: 'chì',
      kHanyuPinyin: '10572.060:huà,é',
      kTGHZ2013: '046.120:chì',
      kXHC1983: '0146.050:chì',
      kVietnamese: 'sứt',
      kHangul: '질:0N',
      kTang: 'chit',
      kJapaneseKun: 'SHIKARU',
      kJapaneseOn: 'SHITSU SHICHI',
      kKorean: 'CIL',
      kSpoofingVariant: 'U+2B738',
      kZVariant: 'U+20B9F',
    },
    unihan_fts: [
      ['U+20B9F', '𠮟', 'kZVariant', 'U+53F1'],
      ['U+2B738', '𫜸', 'kSpoofingVariant', 'U+53F1 U+20B9F'],
      ['U+2F83A', '叱', 'kCompatibilityVariant', 'U+53F1'],
    ],
    unihan_variant: [
      ['kSpoofingVariant', 'U+2B738', '𫜸'],
      ['kZVariant', 'U+20B9F', '𠮟'],
      ['kJoyoKanji', 'U+20B9F', '𠮟'],
    ],
    unihan_variant_inverse: [
      ['kCompatibilityVariant', 'U+2F83A', '叱'],
      ['kSpoofingVariant', 'U+2B738', '𫜸'],
      ['kZVariant', 'U+20B9F', '𠮟'],
    ],
    joyo: [],
    joyo_kangxi: [],
    joyo_kangxi_inverse: [],
    doon: [],
    nyukan: [
      {
        正字の種類: '類字',
        簡体字等の文字コード等: '3832',
        簡体字等のUCS: '㠲',
        正字の文字コード等: '53f1',
        正字のUCS: '叱',
        順位: 1,
      },
      {
        正字の種類: '類字',
        簡体字等の文字コード等: '4097',
        簡体字等のUCS: '䂗',
        正字の文字コード等: '53f1',
        正字のUCS: '叱',
        順位: 1,
      },
      {
        正字の種類: '類字',
        簡体字等の文字コード等: '5391',
        簡体字等のUCS: '厑',
        正字の文字コード等: '53f1',
        正字のUCS: '叱',
        順位: 1,
      },
    ],
    tghb: [
      {
        序号: '3539',
        规范字: '叱',
        级: 2,
        笔画: 5,
        註解: null,
        异体字: [],
      },
    ],
    mji: [
      {
        文字: '叱',
        MJ文字図形名: 'MJ008039',
        対応するUCS: 'U+53F1',
        実装したUCS: 'U+53F1',
        実装したMoji_JohoコレクションIVS: '53F1_E0102',
        実装したSVS: null,
        戸籍統一文字番号: '037710',
        住基ネット統一文字コード: 'J+53F1',
        入管正字コード: '0x53F1',
        入管外字コード: null,
        漢字施策: null,
        対応する互換漢字: null,
        X0213: '1-28-24',
        X0213_包摂連番: null,
        X0213_包摂区分: 0,
        X0212: null,
        MJ文字図形バージョン: '1',
        登記統一文字番号: '00037710',
        '部首・内画数': [[30, 2]],
        総画数: 5,
        読み: ['カ', 'ケ', 'シチ', 'シツ', 'しかる'],
        大漢和: 3248,
        日本語漢字辞典: 1281,
        新大字典: 1741,
        大字源: null,
        大漢語林: 1234,
        更新履歴: [],
        備考: null,
        mjsm: [['JIS包摂規準UCS統合規則', 'U+53F1', '叱']],
      },
      {
        文字: '叱󠄃',
        MJ文字図形名: 'MJ008040',
        対応するUCS: 'U+53F1',
        実装したUCS: null,
        実装したMoji_JohoコレクションIVS: '53F1_E0103',
        実装したSVS: null,
        戸籍統一文字番号: null,
        住基ネット統一文字コード: 'J+AEA9',
        入管正字コード: null,
        入管外字コード: null,
        漢字施策: null,
        対応する互換漢字: null,
        X0213: '1-28-24',
        X0213_包摂連番: 'U078',
        X0213_包摂区分: 2,
        X0212: null,
        MJ文字図形バージョン: '1',
        登記統一文字番号: null,
        '部首・内画数': [[30, 2]],
        総画数: 5,
        読み: ['シチ', 'シツ', 'しかる'],
        大漢和: null,
        日本語漢字辞典: null,
        新大字典: null,
        大字源: null,
        大漢語林: null,
        更新履歴: ['Ver.005.02 「大漢和」を削除'],
        備考: null,
        mjsm: [['JIS包摂規準UCS統合規則', 'U+53F1', '叱']],
      },
    ],
    mjsm_inverse: [
      {
        表: 'JIS包摂規準UCS統合規則',
        文字: '叱',
        MJ文字図形名: 'MJ008039',
        対応するUCS: 'U+53F1',
        実装したUCS: 'U+53F1',
        実装したMoji_JohoコレクションIVS: '53F1_E0102',
        実装したSVS: null,
      },
      {
        表: 'JIS包摂規準UCS統合規則',
        文字: '叱󠄃',
        MJ文字図形名: 'MJ008040',
        対応するUCS: 'U+53F1',
        実装したUCS: null,
        実装したMoji_JohoコレクションIVS: '53F1_E0103',
        実装したSVS: null,
      },
      {
        表: '法務省告示582号別表第四_二',
        文字: '㠲',
        MJ文字図形名: 'MJ000948',
        対応するUCS: 'U+3832',
        実装したUCS: 'U+3832',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
      {
        表: '法務省告示582号別表第四_二',
        文字: '䂗',
        MJ文字図形名: 'MJ002937',
        対応するUCS: 'U+4097',
        実装したUCS: 'U+4097',
        実装したMoji_JohoコレクションIVS: null,
        実装したSVS: null,
      },
    ],
    kdpv: {
      'cjkvi/non-cognate': ['𠮟'],
      'cjkvi/variant': ['𠮟'],
      'hydzd/proper': ['訛'],
      'jisx0213/variant': ['𠮟'],
      'twedu/regular': ['以', '叱'],
      'twedu/variant': ['𠻟'],
    },
  },
] satisfies MojidataResults[])
